# Generated by Django 3.0.8 on 2020-07-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0001_initial'),
        ('manage_epic_capability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_epic_capability',
            name='PROJECT_ID',
            field=models.ManyToManyField(blank=True, default='', related_name='epic_capability_product', to='manage_product.AR_product'),
        ),
    ]
