# Generated by Django 3.0.8 on 2020-08-04 15:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_epic_capability', '0002_auto_20200731_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_epic_capability',
            name='epic_capability_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='Cepic_key', unique_with=('create_dt__month',)),
        ),
    ]
