# Generated by Django 2.2.2 on 2020-01-03 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AR_organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=50, unique=True)),
                ('organization_name', models.CharField(max_length=100)),
                ('organization_url', models.URLField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('subscription_level', models.CharField(blank=True, max_length=50)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person2personsorganization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ar_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default=None, max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('zip', models.IntegerField(blank=True, default='')),
                ('country', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.BigIntegerField(blank=True, default='')),
                ('backup_email', models.EmailField(blank=True, default='', max_length=50)),
                ('user_type', models.CharField(default='Root', max_length=50)),
                ('login_status', models.BooleanField(default=False)),
                ('activate_status', models.BooleanField(default=False)),
                ('verification_status', models.BooleanField(default=False)),
                ('created_by', models.IntegerField(default=0)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(default=0)),
                ('updated_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AR_organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AR_organization_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_key', models.CharField(max_length=50)),
                ('status_desc', models.TextField(blank=True)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person2personsstatuStatus', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendsStatus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ar_organization',
            name='organization_status',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AR_organization_status'),
        ),
        migrations.AddField(
            model_name='ar_organization',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendsorganization', to=settings.AUTH_USER_MODEL),
        ),
    ]
