# Generated by Django 3.0.8 on 2020-07-27 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArTestStoryScoringPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score_for', models.CharField(max_length=50)),
                ('Score_key', models.CharField(max_length=50)),
                ('Keyword', models.TextField()),
                ('Score_one', models.IntegerField(default=0)),
                ('Score_two', models.IntegerField(default=0)),
                ('Score_three', models.IntegerField(default=0)),
                ('Last_Update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Ar test story scoring points',
            },
        ),
    ]
