# Generated by Django 2.2.2 on 2019-12-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191218_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_user',
            name='set_status_set',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ar_user',
            name='org_id',
            field=models.CharField(default=9, max_length=50),
        ),
    ]
