# Generated by Django 2.2.2 on 2019-12-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_ar_user_set_status_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ar_user',
            name='org_id',
        ),
    ]
