# Generated by Django 2.2.2 on 2019-12-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_ar_user_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ar_user',
            name='org_id',
        ),
    ]
