# Generated by Django 2.2.2 on 2019-12-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_ar_user_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_user',
            name='org_id',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
