# Generated by Django 2.2.2 on 2019-12-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_ar_user_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_user',
            name='org_id',
            field=models.IntegerField(default=0),
        ),
    ]
