# Generated by Django 3.0.5 on 2020-07-23 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_product', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AR_BACKLOG_STATUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_status_key', models.CharField(blank=True, max_length=50)),
                ('bl_status_desc', models.TextField(blank=True)),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_by_backlogstatus', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by_backlogstatus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ar backlog status',
            },
        ),
        migrations.CreateModel(
            name='AR_BACKLOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('backlog_score', models.IntegerField()),
                ('Backlog_size', models.IntegerField()),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_Type', models.CharField(blank=True, default='ORG Data', max_length=50)),
                ('BL_STATUS', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_backlogs.AR_BACKLOG_STATUS')),
                ('ORG_ID', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AR_organization')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_by_backlog', to='account.Ar_user')),
                ('owner', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Ar_user')),
                ('product_parent', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backlog_by_product', to='manage_product.AR_product')),
                ('team_list', models.ManyToManyField(blank=True, related_name='backlog_team', to='manage_product.AR_team')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by_backlog', to='account.Ar_user')),
            ],
            options={
                'verbose_name_plural': 'Ar backlog',
            },
        ),
    ]
