# Generated by Django 3.0.8 on 2020-07-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_backlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_backlog',
            name='backlog_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
