# Generated by Django 3.0.8 on 2020-08-04 09:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_backlogs', '0002_ar_backlog_backlog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_backlog',
            name='backlog_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='title', unique_with=('Created_date__month',)),
        ),
    ]
