# Generated by Django 3.0.8 on 2020-07-27 06:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_product', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AR_SCENARIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(blank=True, default='', max_length=100)),
                ('scenario_desc', models.TextField(blank=True, default='')),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ORG_ID', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.AR_organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_by_scenario', to='account.Ar_user')),
                ('product_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_by_scenario', to='manage_product.AR_product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by_scenario', to='account.Ar_user')),
            ],
            options={
                'verbose_name_plural': 'Ar Scenario',
            },
        ),
    ]
