# Generated by Django 3.0.8 on 2020-08-04 14:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar_scenario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_scenario',
            name='scenario_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='scenario_name', unique_with=('created_dt__month',)),
        ),
    ]
