# Generated by Django 3.0.8 on 2020-07-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_testact_set', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artestactset',
            options={'verbose_name_plural': 'Ar Test Action Set'},
        ),
    ]
