# Generated by Django 3.0.8 on 2020-07-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiphistory',
            name='Test_story',
            field=models.IntegerField(default=0, help_text="'0' Equal to 'Unlimited'"),
        ),
        migrations.AddField(
            model_name='subscription',
            name='Test_story',
            field=models.IntegerField(default=0, help_text="'0' Equal to 'Unlimited'"),
        ),
    ]
