# Generated by Django 2.2.4 on 2019-12-18 09:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AR_FEATURE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORG_ID', models.IntegerField(blank=True, default=None)),
                ('Feature_key', models.CharField(blank=True, default='', max_length=50)),
                ('Feature_desc', models.TextField(blank=True, default='')),
                ('Children_us_list', models.CharField(blank=True, default='', max_length=50)),
                ('create_by', models.IntegerField(blank=True, default='')),
                ('create_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 18, 15, 19, 22, 732704))),
                ('update_by', models.IntegerField(blank=True, default='')),
                ('update_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 18, 15, 19, 22, 732704))),
                ('CE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AR_organization')),
            ],
        ),
        migrations.CreateModel(
            name='AR_ITERATIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Iteration_key', models.CharField(blank=True, max_length=50)),
                ('Iteration_desc', models.TextField(blank=True)),
                ('Assoc_us_list', models.CharField(blank=True, max_length=200)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('create_by', models.IntegerField(blank=True)),
                ('create_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 18, 15, 19, 22, 732704))),
                ('update_by', models.IntegerField(blank=True)),
                ('update_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 18, 15, 19, 22, 732704))),
                ('TM_ID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.AR_organization')),
            ],
        ),
        migrations.CreateModel(
            name='AR_US_POINTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_key', models.CharField(blank=True, max_length=50)),
                ('point_desc', models.TextField(blank=True)),
                ('point_short_code', models.CharField(blank=True, max_length=50)),
                ('create_by', models.IntegerField(blank=True)),
                ('create_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 18, 15, 19, 22, 734704))),
                ('update_by', models.IntegerField(blank=True)),
                ('update_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 18, 15, 19, 22, 734704))),
            ],
        ),
        migrations.CreateModel(
            name='AR_US_STATUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_key', models.CharField(blank=True, max_length=50)),
                ('status_desc', models.TextField(blank=True)),
                ('status_shortcode', models.CharField(blank=True, max_length=50)),
                ('create_by', models.IntegerField(blank=True)),
                ('create_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 18, 15, 19, 22, 733704))),
                ('update_by', models.IntegerField(blank=True)),
                ('update_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 18, 15, 19, 22, 733704))),
            ],
        ),
        migrations.CreateModel(
            name='AR_US_TYPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(blank=True, max_length=50)),
                ('type_desc', models.TextField(blank=True)),
                ('type_short_code', models.CharField(blank=True, max_length=50)),
                ('create_by', models.IntegerField(blank=True)),
                ('create_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 18, 15, 19, 22, 733704))),
                ('update_by', models.IntegerField(blank=True)),
                ('update_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 18, 15, 19, 22, 733704))),
            ],
        ),
        migrations.CreateModel(
            name='AR_USER_STORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=50)),
                ('ar_user', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('user_story_type', models.CharField(blank=True, max_length=50)),
                ('story_tri_part_text', models.TextField(blank=True)),
                ('epic_capability', models.CharField(blank=True, max_length=80)),
                ('feature', models.CharField(blank=True, max_length=50)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('ac_readability_score', models.IntegerField(blank=True)),
                ('conversation', models.TextField(blank=True)),
                ('convo_readability_score', models.IntegerField(blank=True)),
                ('attachments', models.CharField(blank=True, max_length=80)),
                ('autoscoring_on', models.BooleanField(blank=True, default=False)),
                ('backlog_parent', models.CharField(blank=True, max_length=100)),
                ('user_story_status', models.CharField(blank=True, max_length=50)),
                ('archive_indicator', models.BooleanField(blank=True, default=False)),
                ('readiness_quality_score', models.IntegerField(blank=True)),
                ('story_points', models.IntegerField(blank=True)),
                ('created_by', models.BigIntegerField(blank=True, default=None, null=True)),
                ('updated_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 18, 15, 19, 22, 735704))),
                ('created_dt', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 18, 15, 19, 22, 735704))),
                ('updated_by', models.BigIntegerField(blank=True, default=None, null=True)),
                ('ft_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ar_user_story.AR_FEATURE')),
                ('itr_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ar_user_story.AR_ITERATIONS')),
                ('usp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ar_user_story.AR_US_POINTS')),
                ('uss_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ar_user_story.AR_US_STATUS')),
                ('ust_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ar_user_story.AR_US_TYPE')),
            ],
        ),
    ]
