# Generated by Django 2.2.2 on 2019-12-19 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_user_story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_feature',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 20, 27, 485234)),
        ),
        migrations.AlterField(
            model_name='ar_feature',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 20, 27, 485280)),
        ),
        migrations.AlterField(
            model_name='ar_iterations',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 20, 27, 485996)),
        ),
        migrations.AlterField(
            model_name='ar_iterations',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 20, 27, 486031)),
        ),
        migrations.AlterField(
            model_name='ar_us_points',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 20, 27, 487761)),
        ),
        migrations.AlterField(
            model_name='ar_us_points',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 20, 27, 487801)),
        ),
        migrations.AlterField(
            model_name='ar_us_status',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 20, 27, 487207)),
        ),
        migrations.AlterField(
            model_name='ar_us_status',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 20, 27, 487249)),
        ),
        migrations.AlterField(
            model_name='ar_us_type',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 20, 27, 486646)),
        ),
        migrations.AlterField(
            model_name='ar_us_type',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 20, 27, 486689)),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 20, 27, 488780)),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='updated_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 20, 27, 488755)),
        ),
    ]
