# Generated by Django 2.2.2 on 2019-12-19 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_user_story', '0002_auto_20191219_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_feature',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 25, 7, 275416)),
        ),
        migrations.AlterField(
            model_name='ar_feature',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 25, 7, 275461)),
        ),
        migrations.AlterField(
            model_name='ar_iterations',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 25, 7, 276283)),
        ),
        migrations.AlterField(
            model_name='ar_iterations',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 25, 7, 276320)),
        ),
        migrations.AlterField(
            model_name='ar_us_points',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 25, 7, 278043)),
        ),
        migrations.AlterField(
            model_name='ar_us_points',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 25, 7, 278079)),
        ),
        migrations.AlterField(
            model_name='ar_us_status',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 25, 7, 277491)),
        ),
        migrations.AlterField(
            model_name='ar_us_status',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 25, 7, 277530)),
        ),
        migrations.AlterField(
            model_name='ar_us_type',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 25, 7, 276930)),
        ),
        migrations.AlterField(
            model_name='ar_us_type',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 25, 7, 276967)),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 25, 7, 279083)),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='updated_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 25, 7, 279058)),
        ),
    ]
