# Generated by Django 2.2.2 on 2019-12-19 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_user_story', '0003_auto_20191219_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_feature',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 29, 30, 712840)),
        ),
        migrations.AlterField(
            model_name='ar_feature',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 29, 30, 712886)),
        ),
        migrations.AlterField(
            model_name='ar_iterations',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 29, 30, 713729)),
        ),
        migrations.AlterField(
            model_name='ar_iterations',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 29, 30, 713766)),
        ),
        migrations.AlterField(
            model_name='ar_us_points',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 29, 30, 715559)),
        ),
        migrations.AlterField(
            model_name='ar_us_points',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 29, 30, 715599)),
        ),
        migrations.AlterField(
            model_name='ar_us_status',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 29, 30, 714995)),
        ),
        migrations.AlterField(
            model_name='ar_us_status',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 29, 30, 715035)),
        ),
        migrations.AlterField(
            model_name='ar_us_type',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 29, 30, 714392)),
        ),
        migrations.AlterField(
            model_name='ar_us_type',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 29, 30, 714430)),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 29, 30, 716611)),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='updated_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 29, 30, 716587)),
        ),
    ]
