# Generated by Django 2.2.2 on 2020-01-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0001_initial'),
        ('manage_features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ar_feature',
            name='User_story',
        ),
        migrations.AddField(
            model_name='ar_feature',
            name='User_story',
            field=models.ForeignKey(blank=True, default='', on_delete='models.SET_NULL', to='user_story_view.AR_USER_STORY'),
        ),
    ]
