# Generated by Django 3.0.8 on 2020-07-27 06:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArAcadenyEmailForRecavedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=120)),
                ('Status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Ar Acadeny Emailes For Recaved Email',
            },
        ),
        migrations.CreateModel(
            name='ArFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=50)),
                ('feedback_nature', models.TextField(blank=True)),
                ('feedback_information', models.TextField()),
                ('attachments', models.FileField(upload_to='feedback/')),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_feedback', to='account.Ar_user')),
            ],
            options={
                'verbose_name_plural': 'Ar feedback',
            },
        ),
        migrations.CreateModel(
            name='ArSendFeedbackEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_id_for_sent', to='feedback.ArFeedback')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_id_for_sent', to='account.Ar_user')),
            ],
            options={
                'verbose_name_plural': 'Ar send feedback email',
            },
        ),
        migrations.CreateModel(
            name='ArEmailSendToAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Email', models.CharField(blank=True, max_length=120, null=True)),
                ('Email_Subjects', models.CharField(blank=True, max_length=120, null=True)),
                ('invited_by', models.CharField(blank=True, max_length=120, null=True)),
                ('Subscription_Plan', models.CharField(blank=True, max_length=120, null=True)),
                ('Mail_send', models.BooleanField(default=False)),
                ('Mail_send_date', models.DateTimeField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('Ar_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ar_user_ArEmailSendToAdmin', to='account.Ar_user')),
                ('ORG_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_id_ArEmailSendToAdmin', to='account.AR_organization')),
            ],
            options={
                'verbose_name_plural': 'Ar Email Send To Admin',
            },
        ),
    ]
