# Generated by Django 3.0.8 on 2020-08-04 09:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_user_story',
            name='user_story_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='title', unique_with=('Created_date__month',)),
        ),
    ]
