# Generated by Django 3.0.8 on 2020-08-04 11:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0003_auto_20200804_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_us_status',
            name='user_status_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='status_key', unique_with=('create_dt__month',)),
        ),
        migrations.AddField(
            model_name='ar_us_type',
            name='user_type_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='type_key', unique_with=('create_dt__month',)),
        ),
    ]
