# Generated by Django 3.0.8 on 2020-08-08 09:48

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_story_view', '0004_auto_20200804_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(blank=True, max_length=50, unique=True)),
                ('page_slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='page_name', unique_with=('create_dt__month',))),
                ('topic', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('information', models.TextField(blank=True)),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_by_help_text', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by_help_text', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ar Help Text',
            },
        ),
    ]
