# Generated by Django 2.2.2 on 2019-12-19 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_user_story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_feature',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 36, 21, 466501)),
        ),
        migrations.AlterField(
            model_name='ar_feature',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 36, 21, 466545)),
        ),
        migrations.AlterField(
            model_name='ar_iterations',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 36, 21, 467396)),
        ),
        migrations.AlterField(
            model_name='ar_iterations',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 36, 21, 467433)),
        ),
        migrations.AlterField(
            model_name='ar_us_points',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 36, 21, 469197)),
        ),
        migrations.AlterField(
            model_name='ar_us_points',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 36, 21, 469238)),
        ),
        migrations.AlterField(
            model_name='ar_us_status',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 36, 21, 468631)),
        ),
        migrations.AlterField(
            model_name='ar_us_status',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 36, 21, 468670)),
        ),
        migrations.AlterField(
            model_name='ar_us_type',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 36, 21, 468066)),
        ),
        migrations.AlterField(
            model_name='ar_us_type',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 36, 21, 468102)),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 36, 21, 470254)),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='updated_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 19, 14, 36, 21, 470229)),
        ),
    ]
