# Generated by Django 2.2.2 on 2019-12-19 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ar_user_story', '0002_auto_20191219_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_feature',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ar_feature',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ar_iterations',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ar_iterations',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ar_us_points',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ar_us_points',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ar_us_status',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ar_us_status',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ar_us_type',
            name='create_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ar_us_type',
            name='update_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ar_user_story',
            name='updated_dt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
