# Generated by Django 3.0.8 on 2020-08-22 09:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_and_patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_category',
            name='category_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name'),
        ),
    ]
