# Generated by Django 2.2.2 on 2019-12-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191219_1537'),
        ('manage_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ar_team',
            unique_together={('Team_name', 'ORG_id')},
        ),
    ]
