# Generated by Django 3.0.8 on 2020-08-04 12:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_product',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='Product_name', unique_with=('create_dt__month',)),
        ),
        migrations.AddField(
            model_name='ar_team',
            name='team_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='Team_name', unique_with=('create_dt__month',)),
        ),
    ]
