# Generated by Django 3.0.8 on 2020-07-27 06:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_story_view', '0001_initial'),
        ('user_story_points', '0001_initial'),
        ('account', '0001_initial'),
        ('business_value', '0001_initial'),
        ('manage_backlogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AR_JOB_STORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('story_tri_part_text', models.TextField(blank=True)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('ac_readability_score', models.BigIntegerField(blank=True)),
                ('conversation', models.TextField(blank=True)),
                ('convo_readability_score', models.BigIntegerField(blank=True)),
                ('autoscoring_on', models.BooleanField(blank=True, default=False)),
                ('archive_indicator', models.BooleanField(blank=True, default=False)),
                ('readiness_quality_score', models.BigIntegerField(blank=True)),
                ('updated_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_Type', models.CharField(blank=True, default='ORG Data', max_length=50)),
                ('BV_ID', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='job_story_by_business_value', to='business_value.AR_BUSINESS_VALUE')),
                ('ORG_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.AR_organization')),
                ('UST_ID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_story_view.AR_US_TYPE')),
                ('ar_user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_story_ar_user', to='account.Ar_user')),
                ('backlog_parent', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='job_story_by_backlog', to='manage_backlogs.AR_BACKLOG')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_by_job_story', to='account.Ar_user')),
                ('job_story_status', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_story_view.AR_US_STATUS')),
                ('owner', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Ar_user')),
                ('story_points', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_story_points', to='user_story_points.ArUserStoryPoints')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by_job_story', to='account.Ar_user')),
            ],
            options={
                'verbose_name_plural': 'Ar job story',
            },
        ),
        migrations.CreateModel(
            name='job_story_file_attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, default='None', null=True, upload_to='attachments/job_story/')),
                ('job_story', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='job_story_file_attachment', to='job_story_view.AR_JOB_STORY')),
            ],
            options={
                'verbose_name_plural': 'Ar job story attachment',
            },
        ),
    ]
