# Generated by Django 3.0.8 on 2020-07-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STRIPE_SECRET_KEY', models.CharField(max_length=80)),
                ('STRIPE_PUBLISHABLE_KEY', models.CharField(max_length=100)),
                ('currency_type', models.CharField(max_length=100)),
                ('Payment_Method', models.CharField(default='Stripe', max_length=100)),
            ],
            options={
                'db_table': 'Stripe Account',
            },
        ),
    ]
