# Generated by Django 2.2.2 on 2019-12-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191218_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_user',
            name='org_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person2personsorganization', to='account.AR_organization'),
        ),
    ]
