# Generated by Django 3.0.8 on 2020-07-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_story_view', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ar_test_story',
            name='test_story_status',
        ),
    ]
