# Generated by Django 3.0.8 on 2020-07-27 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_story_view', '0001_initial'),
        ('test_story_view', '0002_remove_ar_test_story_test_story_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ar_test_story',
            name='test_story_status',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_story_view.AR_US_STATUS'),
        ),
    ]
