# Generated by Django 3.0.8 on 2020-09-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_story_view', '0003_ar_test_story_test_story_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ar_test_story',
            options={'verbose_name_plural': 'Ar bdd tdd story'},
        ),
    ]
