# Generated by Django 3.0.8 on 2020-07-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='import_files_data',
            options={'verbose_name_plural': 'Import files data (Default data)'},
        ),
    ]
