# Generated by Django 2.2.2 on 2020-01-03 05:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('manage_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AR_ITERATIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Iteration_key', models.CharField(blank=True, max_length=50)),
                ('Iteration_desc', models.TextField(blank=True)),
                ('Assoc_us_list', models.CharField(blank=True, max_length=200)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ORG_ID', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='account.AR_organization')),
                ('TM_ID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manage_product.AR_team')),
                ('create_by', models.ForeignKey(on_delete='models.SET_NULL', related_name='create_by_iterations', to='account.Ar_user')),
                ('update_by', models.ForeignKey(on_delete='models.SET_NULL', related_name='update_by_iterations', to='account.Ar_user')),
            ],
        ),
    ]
