# Generated by Django 3.0.8 on 2020-08-04 12:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_value', '0002_ar_business_value_business_value_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ar_business_value',
            name='business_value_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='bus_value_txt_code', unique_with=('ORG_ID',)),
        ),
    ]
