# Generated by Django 2.2.2 on 2019-12-17 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AR_FEATURE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_key', models.CharField(blank=True, default=None, max_length=50)),
                ('Feature_desc', models.TextField(blank=True, default=None)),
                ('Children_us_list', models.CharField(blank=True, default=None, max_length=50)),
                ('ORG_ID', models.IntegerField(blank=True, default=None)),
                ('create_by', models.IntegerField(blank=True, default=None)),
                ('create_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('update_by', models.IntegerField(blank=True, default=None)),
                ('update_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('CE_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AR_organization')),
            ],
        ),
        migrations.CreateModel(
            name='AR_ITERATIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Iteration_key', models.CharField(max_length=50)),
                ('Iteration_desc', models.TextField()),
                ('Assoc_us_list', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('create_by', models.IntegerField()),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.IntegerField()),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('TM_ID', models.ForeignKey(on_delete='models.CASCADE', to='account.AR_organization')),
            ],
        ),
        migrations.CreateModel(
            name='AR_US_POINTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_key', models.CharField(max_length=50)),
                ('point_desc', models.TextField()),
                ('point_short_code', models.CharField(max_length=50)),
                ('create_by', models.IntegerField()),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.IntegerField()),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AR_US_STATUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_key', models.CharField(max_length=50)),
                ('status_desc', models.TextField()),
                ('status_shortcode', models.CharField(max_length=50)),
                ('create_by', models.IntegerField()),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.IntegerField()),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AR_US_TYPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(max_length=50)),
                ('type_desc', models.TextField()),
                ('type_short_code', models.CharField(max_length=50)),
                ('create_by', models.IntegerField()),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.IntegerField()),
                ('update_dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AR_USER_STORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('ar_user', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=80)),
                ('user_story_type', models.CharField(max_length=50)),
                ('story_tri_part_text', models.TextField()),
                ('epic_capability', models.CharField(max_length=80)),
                ('feature', models.CharField(max_length=50)),
                ('acceptance_criteria', models.TextField()),
                ('ac_readability_score', models.IntegerField()),
                ('conversation', models.TextField()),
                ('convo_readability_score', models.IntegerField()),
                ('attachments', models.CharField(max_length=80)),
                ('autoscoring_on', models.BooleanField(default=False)),
                ('backlog_parent', models.CharField(max_length=100)),
                ('user_story_status', models.CharField(max_length=50)),
                ('archive_indicator', models.BooleanField(default=False)),
                ('readiness_quality_score', models.IntegerField()),
                ('story_points', models.IntegerField()),
                ('created_by', models.BigIntegerField()),
                ('updated_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.BigIntegerField()),
                ('bl_id', models.ForeignKey(on_delete='models.SET_NULL', related_name='value_bl_id', to='ar_user_story.AR_FEATURE')),
                ('ft_id', models.ForeignKey(on_delete='models.SET_NULL', related_name='value_ar_feature', to='ar_user_story.AR_FEATURE')),
                ('itr_id', models.ForeignKey(on_delete='models.SET_NULL', related_name='value_ar_iterations', to='ar_user_story.AR_ITERATIONS')),
                ('usp_id', models.ForeignKey(on_delete='models.SET_NULL', related_name='value_usp_id', to='ar_user_story.AR_US_POINTS')),
                ('uss_id', models.ForeignKey(on_delete='models.SET_NULL', related_name='value_uss_id', to='ar_user_story.AR_US_STATUS')),
                ('ust_id', models.ForeignKey(on_delete='models.SET_NULL', related_name='value_ar_us_type', to='ar_user_story.AR_US_TYPE')),
            ],
        ),
    ]
